# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Week.create([
  { :date_start => "2013-11-21", :date_finished => "2013-11-27", :created_at => "2013-11-21 06:44:44", :updated_at => "2013-11-21 06:44:44" },
  { :date_start => "2013-11-28", :date_finished => "2013-12-04", :created_at => "2013-11-21 06:45:38", :updated_at => "2013-11-21 06:45:38" },
  { :date_start => "2013-12-05", :date_finished => "2013-12-13", :created_at => "2013-11-21 06:46:01", :updated_at => "2013-11-21 06:47:05" },
  { :date_start => "2013-12-14", :date_finished => "2013-12-20", :created_at => "2013-11-21 07:05:00", :updated_at => "2013-11-21 07:05:00" },
  { :date_start => "2013-12-21", :date_finished => "2013-12-27", :created_at => "2013-11-21 07:06:09", :updated_at => "2013-11-21 07:06:09" },
  { :date_start => "2013-12-28", :date_finished => "2014-01-03", :created_at => "2013-11-21 07:06:09", :updated_at => "2013-11-21 07:06:09" },
  { :date_start => "2014-01-04", :date_finished => "2014-01-10", :created_at => "2013-11-21 07:06:09", :updated_at => "2013-11-21 07:06:09" },
  { :date_start => "2014-01-11", :date_finished => "2014-01-17", :created_at => "2013-11-21 07:06:09", :updated_at => "2013-11-21 07:06:09" },
  { :date_start => "2014-01-18", :date_finished => "2014-01-24", :created_at => "2013-11-21 07:06:09", :updated_at => "2013-11-21 07:06:09" },
  { :date_start => "2014-01-25", :date_finished => "2014-01-31", :created_at => "2013-11-21 07:06:09", :updated_at => "2013-11-21 07:06:09" },
  { :date_start => "2014-02-01", :date_finished => "2014-02-07", :created_at => "2013-11-21 07:06:09", :updated_at => "2013-11-21 07:06:09" },
  { :date_start => "2014-02-08", :date_finished => "2014-02-14", :created_at => "2013-11-21 07:06:09", :updated_at => "2013-11-21 07:06:09" },
  { :date_start => "2014-02-15", :date_finished => "2014-02-21", :created_at => "2013-11-21 07:06:09", :updated_at => "2013-11-21 07:06:09" },
  { :date_start => "2014-02-22", :date_finished => "2014-02-28", :created_at => "2013-11-21 07:06:09", :updated_at => "2013-11-21 07:06:09" },
  { :date_start => "2014-03-01", :date_finished => "2014-03-07", :created_at => "2013-11-21 07:06:09", :updated_at => "2013-11-21 07:06:09" },
  { :date_start => "2014-03-08", :date_finished => "2014-03-14", :created_at => "2013-11-21 07:06:09", :updated_at => "2013-11-21 07:06:09" }
], :without_protection => true )


